---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Install NGINX
  yum:
    name: nginx
    state: present
  notify: restart nginx

- name: Create web directory
  file:
    path: /usr/share/nginx/html
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

- name: Configure nginx virtual host
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Ensure nginx service is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: yes
